import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fold, runFoldJob } from "../src/fold.mjs";
import { parseSummaryBody } from "../src/summary.mjs";
import { tmpBundle, tmpGitRepo } from "./helpers.mjs";
process.env.MEMORY_SYNC_INLINE = "1";
const fx = path.join(import.meta.dirname, "fixtures", "transcripts", "pi.jsonl");
const observer = `sh -c 'grep -q "You distill" - && echo "Keep pnpm <- $(cat "$MEMORY_PROMPT_FILE" | grep -o "\\[[a-f0-9]\\{12\\}\\]" | head -1 | tr -d "[]")" || echo "[high] User requires pnpm, never npm | a1b2c3d4"'`;
test("fold skips under threshold, folds when forced, appends observations with sources, finalize stabilizes", () => {
  const b = tmpBundle(); const repo = tmpGitRepo("git@github.com:a/b.git");
  const opts = { session: "pi:session/01a0457b", actor: "pi/kimi-k3", transcript: fx, cwd: repo, format: "pi", summarizeCmd: observer, settings: { observeAfterTokens: 8000, reflectAfterTokens: 20000, observationsMaxTokens: 20000, observationsTargetTokens: 10000 } };
  assert.equal(fold(b, opts).status, "skipped");
  const r = runFoldJob(b, { ...opts, force: true });
  assert.equal(r.observations, 1);
  const dir = b.dir("github.com/a/b");
  const [{ rel, concept }] = b.listConcepts(dir).filter((e) => e.concept.type === "Session Summary");
  assert.match(rel, /session-summaries\/\d{8}T\d{6}Z-pi-kimi-k3\.md$/);
  assert.equal(concept.status, "draft");
  const body = parseSummaryBody(concept.body);
  assert.equal(body.observations[0].content, "User requires pnpm, never npm"); assert.equal(body.observations[0].relevance, "high");
  assert.ok(concept.sources.some((s) => s.id === body.observations[0].id && s.resource === "a1b2c3d4"));
  const state = JSON.parse(fs.readFileSync(b.statePath("pi-session-01a0457b.json"), "utf8"));
  assert.equal(state.transcriptBytes, fs.statSync(fx).size);
  assert.equal(fold(b, opts).status, "skipped");
  assert.equal(runFoldJob(b, { ...opts, force: true }).observations, 0);
  runFoldJob(b, { ...opts, finalize: true });
  assert.equal(b.readConcept(rel).status, "stable");
});
test("reflector runs when observed tokens cross the threshold", () => {
  const b = tmpBundle(); const repo = tmpGitRepo("git@github.com:a/b.git");
  const opts = { session: "pi:session/r", actor: "pi/kimi-k3", transcript: fx, cwd: repo, format: "pi", summarizeCmd: observer, force: true, settings: { observeAfterTokens: 1, reflectAfterTokens: 1, observationsMaxTokens: 20000, observationsTargetTokens: 10000 } };
  const r = runFoldJob(b, opts);
  assert.equal(r.reflected, true);
  const [{ concept }] = b.listConcepts(b.dir("github.com/a/b"));
  const body = parseSummaryBody(concept.body);
  assert.equal(body.reflections.length, 1); assert.deepEqual(body.reflections[0].supports, [body.observations[0].id]);
});
